### ISSUE TITLE
Feedback for chapter 3

### ISSUE THREAD

**Issue by ronaldploeger** [KristianLyng/varnishfoo#17]
Hi Kristian,
1. You mention VSM in chapter 3 but it is not mentioned in appendix A. Generally I think it would be nice to give the full name in addition to the acronym when used for the first time.
2. You write "In the example above varnishd -b localhost:8080 was used." But the -b option was not used in the example.
3. You write "Notice how varnishadm works with zero arguments, but if you start adding -T you also have to specify the -S." but in the example above you do it the other way round. First call varnishadm with arguments and then without. I found this confusing.
4. You write "-d can be used to test as it will connect your terminal to the Varnish CLI". You do not explain enough what the -d option does and when/how to use it. 
5. You write "-n dir is used to control Varnish working directory." but you do not mention that it is used to specify the name of the varnish instance and that to specify a full path is just one variation.
6. You write "You can also provide -i to set an identity. This can be used in VCL to identify a Varnish instance."  I would expect an example with this. If it is too advanced for chapter 3 I would put it into Appendix B.

All the best, 
Ronald

**Comment by KristianLyng** [comment]
Thanks, these are all good points!

I think I've addressed most of them now, except -d. I'll think a bit more about it, because I don't really want people to use it, but since I've used it in examples, it would be strange not to mention it at all. I think I might just re-do the examples where it's used anyway, using varnishadm instead.

For VSM and -i I simply omit them. The acronyms are often downright wrong, and VSM is one such case (it's not documented, refers some times to the counters in the shmlog, and other times to the whole thing...). I might revisit VSM specifically in the appendix/wiki page so that particular ambiguity is resolved - or at least alleviated.

I'll keep this open until I've figured out what to do with -d.

**Comment by ronaldploeger** [comment]
The sentence "This, combined with Varnish developers habit of frequently changing Varnish default behavior to the better means that very changes are needed to get a basic Varnish installation going."  seems to be hanging in there somehow but I do not get what you are trying to tell the reader with it it this context. Plus you already mentioned earlier that default values are changed frequently.

**Comment by KristianLyng** [comment]
Yeah,  I did a full read through of the chapter earlier today and this is one of the things that need fixing, along with several other issues I've written down.

**Comment by KristianLyng** [comment]
I've basically incorporated all of this for now, including removing the demo with -d and thus not having to document it (far easier to read the example now anyway). Also rewrote the design-chapter, but I have a feeling I'll revisit that again, it still doesn't feel right. But at least it's useful.

Closing the ticket since the specific issues are handled. Thanks again for taking the time to read the material and give feedback.
